syntax = "proto3";

option csharp_namespace = "SCEAMS.NotificationService";

package sceams.notification;

service Notification {
  rpc PublishEventNotification (EventNotificationRequest) returns (NotificationAck);
}

message EventNotificationRequest {
  int32 event_id = 1;
  string event_title = 2;
  string event_status = 3;
  int32 recipient_user_id = 4;
  string notification_type = 5;
  string correlation_id = 6;
}

message NotificationAck {
  bool accepted = 1;
  string correlation_id = 2;
  string message = 3;
}
